import { useState } from "react";
import { useLocation } from "wouter";
import { ChevronDown, ChevronRight, Menu, ShoppingCart, TrendingDown, TrendingUp, X } from "lucide-react";

const VIDEO_URL = "https://d8j0ntlcm91z4.cloudfront.net/user_38xzZboKViGWJOttwIXH07lWA1P/hf_20260424_064411_9e9d7f84-9277-41f4-ab10-59172d89e6be.mp4";
const POSTER_URL = "https://images.unsplash.com/photo-1557683316-973673baf926?w=1600&q=60";

function FlowerMark() {
  const petals = Array.from({ length: 8 }, (_, index) => { const angle = (index * Math.PI) / 4; return { x: 16 + Math.cos(angle) * 10, y: 16 + Math.sin(angle) * 10 }; });
  return <svg viewBox="0 0 32 32" className="size-7 sm:size-8" aria-label="Stack logo" role="img">{petals.map((petal, index) => <circle key={index} cx={petal.x} cy={petal.y} r="3.5" fill="#ef4d23" />)}<circle cx="16" cy="16" r="3.5" fill="#ef4d23" /></svg>;
}

function Gauge({ value, color = "#ef4d23", showLabels, min = "389K", max = "425K" }: { value: number; color?: string; showLabels?: boolean; min?: string; max?: string }) {
  const ticks = Array.from({ length: 40 }, (_, index) => { const angle = Math.PI + (index / 39) * Math.PI; const active = index < Math.round((value / 100) * 40); return <line key={index} x1={100 + Math.cos(angle) * 68} y1={100 + Math.sin(angle) * 68} x2={100 + Math.cos(angle) * 80} y2={100 + Math.sin(angle) * 80} stroke={active ? color : "#d4d4d8"} strokeWidth="2.5" strokeLinecap="round" />; });
  return <div className="mx-auto mt-1 max-w-[260px]"><svg viewBox="0 0 200 120" className="w-full" aria-label={`${value}%`}>
    {ticks}<text x="100" y="105" textAnchor="middle" fontSize="22" fontWeight="600" fill="#171717">{value}%</text>
  </svg>{showLabels && <div className="-mt-2 flex justify-between text-[11px] text-neutral-500"><span>{min}</span><span>{max}</span></div>}</div>;
}
function Toggle({ active, inactive }: { active: string; inactive: string }) { return <div className="mt-4 flex rounded-full bg-neutral-100 p-1 text-[11px] font-medium text-neutral-400"><span className="rounded-full bg-white px-3 py-1.5 text-neutral-800 shadow-sm">{active}</span><span className="px-3 py-1.5">{inactive}</span></div>; }
function Metric({ label, value, trailing, note }: { label: string; value: string; trailing: React.ReactNode; note: string }) { return <><div className="flex items-center justify-between text-[13px]"><span className="font-semibold text-[#ef4d23]">{label}</span><span className="text-neutral-400">{trailing}</span></div><div className="mt-4 flex items-center gap-2"><span className="text-[28px] font-semibold tracking-[-.06em] text-neutral-900">{value}</span></div><div className="mt-1 text-[11px] text-neutral-400">{note}</div></>; }

function DashboardPreview() {
  return <div className="mx-auto w-full max-w-[880px] rounded-3xl bg-[#f5f2ee] p-4 shadow-[0_30px_80px_rgba(75,58,44,.14)] sm:p-6"><div className="grid grid-cols-1 gap-3 sm:grid-cols-2 sm:gap-4 lg:grid-cols-3">
    <article className="min-h-[290px] rounded-2xl bg-white p-5 shadow-[0_2px_12px_rgba(20,20,20,.04)]"><Metric label="Clicks" value="6,896" trailing="This Month" note="Compared to yesterday" /><span className="mt-[-29px] flex w-fit translate-x-[114px] items-center gap-1 rounded-full bg-red-50 px-2 py-0.5 text-[11px] font-semibold text-red-600"><TrendingDown size={11} /> -3,382 (33%)</span><div className="mt-4 text-center text-[11px] text-neutral-500">Month Target achieved</div><Gauge value={92} showLabels /><Toggle active="Impressions" inactive="Clicks" /></article>
    <article className="flex min-h-[290px] flex-col gap-3 rounded-2xl bg-white p-5 shadow-[0_2px_12px_rgba(20,20,20,.04)]"><div className="flex items-center justify-between text-[13px]"><span className="font-semibold text-[#ef4d23]">Form</span><span className="text-neutral-400">Quick setup</span></div><label className="text-[12px] text-neutral-700">Show figures for<span className="mt-1 flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-2 text-[12px] font-medium text-neutral-800">This month <ChevronDown size={14} className="text-neutral-400" /></span></label><label className="text-[12px] text-neutral-700">Compare period by<span className="mt-1 flex items-center justify-between rounded-lg border border-neutral-200 px-3 py-2 text-[12px] font-medium text-neutral-800">Month-to-date (MTD) <ChevronDown size={14} className="text-neutral-400" /></span></label><label className="text-[12px] text-neutral-700">Ste targets (This month)<span className="mt-1 flex items-center gap-1 rounded-lg border border-neutral-200 px-3 py-2 text-[12px] text-neutral-800"><span className="text-neutral-400">#</span><input aria-label="Ste targets this month" defaultValue="10" className="w-full outline-none" /></span></label><label className="text-[12px] text-neutral-700">Ste targets (This year)<span className="mt-1 flex items-center gap-1 rounded-lg border border-neutral-200 px-3 py-2 text-[12px] text-neutral-800"><span className="text-neutral-400">#</span><input aria-label="Ste targets this year" defaultValue="100" className="w-full outline-none" /></span></label><div className="mt-auto flex items-center gap-4 border-t border-neutral-100 pt-3"><button className="rounded-lg bg-[#ef4d23] px-5 py-2 text-[12px] font-semibold text-white">Save</button><button className="text-[12px] text-neutral-500 underline underline-offset-2">Cancel</button><X size={15} className="ml-auto text-neutral-300" /></div></article>
    <article className="min-h-[290px] rounded-2xl bg-white p-5 shadow-[0_2px_12px_rgba(20,20,20,.04)]"><Metric label="Video Starts" value="0" trailing="today" note="Compared to yesterday" /><span className="mt-[-29px] flex w-fit translate-x-[72px] items-center gap-1 rounded-full bg-neutral-100 px-2 py-0.5 text-[11px] font-semibold text-neutral-500"><TrendingUp size={11} /> 0</span><div className="mt-4"><Gauge value={68} color="#9ca3af" /></div><Toggle active="Video Clicks" inactive="Video Starts" /></article>
  </div></div>;
}

export default function Landing() {
  const [, setLocation] = useLocation(); const [menuOpen, setMenuOpen] = useState(false); const goToWorkspace = () => { setMenuOpen(false); setLocation("/workspace"); };
  return <main className="min-h-screen w-full bg-[#ededed] p-3 font-[Inter,sans-serif] sm:p-4"><section className="relative h-[calc(100vh-24px)] min-h-[720px] w-full overflow-hidden rounded-2xl bg-[#d9d9d9] sm:h-[calc(100vh-32px)] sm:rounded-3xl"><video className="pointer-events-none absolute inset-0 h-full w-full object-cover" autoPlay loop muted playsInline preload="auto" disableRemotePlayback webkit-playsinline="true" x5-playsinline="true" poster={POSTER_URL} aria-hidden="true"><source src={VIDEO_URL} type="video/mp4" /></video><div className="absolute inset-0 bg-white/10" /><div className="relative z-10 flex h-full min-h-[720px] flex-col">
    <nav className="flex justify-center px-3 pt-4 sm:px-4 sm:pt-6"><div className="relative flex w-full max-w-[760px] items-center rounded-full border border-neutral-200 bg-white py-2 pl-2 pr-2 shadow-sm"><button onClick={() => setLocation("/")} className="shrink-0 rounded-full hover:bg-neutral-100"><FlowerMark /></button><div className="ml-4 hidden items-center gap-6 text-[14px] font-medium text-neutral-500 md:flex"><button className="flex items-center gap-1.5 text-neutral-900"><span className="size-[1.5px] rounded-full bg-black" /> Home</button><button>Features</button><button>About</button><button className="flex items-center gap-1 text-[#ef4d23]">Pages <ChevronDown size={13} /></button></div><div className="ml-auto flex items-center gap-2"><ShoppingCart size={16} className="mr-2 hidden text-neutral-500 md:block" /><button onClick={goToWorkspace} className="flex items-center gap-2 rounded-full bg-[#ef4d23] py-1.5 pl-4 pr-1.5 text-[11px] font-semibold text-white hover:bg-[#db421b] sm:pl-5"><span className="hidden sm:inline">Get early access</span><span className="sm:hidden">Early access</span><span className="grid size-6 place-items-center rounded-full bg-white/20"><ChevronRight size={14} /></span></button><button className="ml-1 rounded-full p-2 text-neutral-700 md:hidden" onClick={() => setMenuOpen(open => !open)} aria-label="Open menu">{menuOpen ? <X size={17} /> : <Menu size={17} />}</button></div>{menuOpen && <div className="absolute left-2 right-2 top-full z-20 mt-2 rounded-2xl border border-neutral-200 bg-white p-3 text-sm text-neutral-700 shadow-lg md:hidden"><button onClick={goToWorkspace} className="block w-full rounded-xl px-3 py-2 text-left font-medium text-neutral-900">Home</button><button className="block w-full rounded-xl px-3 py-2 text-left">Features</button><button className="block w-full rounded-xl px-3 py-2 text-left">About</button><button className="block w-full rounded-xl px-3 py-2 text-left text-[#ef4d23]">Pages</button></div>}</div></nav>
    <div className="flex flex-col items-center px-4 pb-8 pt-10 text-center sm:pb-12 sm:pt-16"><div className="inline-flex items-center gap-2 rounded-full bg-white px-4 py-1.5 text-[13px] font-medium text-neutral-700 shadow-sm"><span className="size-1.5 rounded-full bg-[#ef4d23]" /> Stack</div><h1 className="mt-5 max-w-4xl text-[clamp(36px,8vw,72px)] font-medium leading-[1.05] tracking-[-.02em] text-[#131313] sm:mt-6">Build <span className="font-serif italic font-normal" style={{ fontFamily: "'Instrument Serif', serif" }}>Worlds</span><br />and apps of tomorrow</h1><p className="mt-4 px-2 text-[clamp(13px,3.5vw,16px)] text-neutral-700 sm:mt-6">The AI workspace for building games, applications, and websites.</p><button onClick={goToWorkspace} className="mt-6 inline-flex items-center gap-3 rounded-full bg-[#0b0f1a] py-2 pl-6 pr-2 text-[14px] text-white hover:bg-[#1d2433] sm:mt-8 sm:pl-7">Start building<span className="grid size-6 place-items-center rounded-full bg-white/15 sm:size-7"><ChevronRight size={15} /></span></button></div><div className="mt-auto px-3 sm:px-4"><DashboardPreview /></div>
  </div></section></main>;
}
